import localFont from "next/font/local";
import "./globals.css";
import { TransactionProvider } from "@/components/context";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "react-hot-toast";
import MainLayout from "@/components/MainLayout";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Lottery Dapp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <TransactionProvider>
        <MainLayout>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <NextTopLoader />
            <Toaster position="top-right" reverseOrder={false} />
            {children}
          </body>
        </MainLayout>
      </TransactionProvider>
    </html>
  );
}
